version: '3.5'
services:
  server:
    image: $chad_docker_registry/challenges/smell_2_server
    environment:
      - CHALLENGE_IP=192.168.142.1/17
    networks:
      - challenge
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  client:
    image: $chad_docker_registry/challenges/smell_2_client
    environment:
      - CHALLENGE_IP=192.168.142.2/17
      - HOST=192.168.142.1
    networks:
      - challenge
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
