version: '3.5'
services:
  app:
    image: $chad_docker_registry/challenges/whisper
    environment:
      - CHALLENGE_IP=192.168.145.1/17
    networks:
      - challenge
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
