version: '3.5'
services:
  host:
    image: $chad_docker_registry/challenges/pf_senseless/host_signed
    environment:
      - DEBUGGER_IP=192.168.148.2/17
    networks:
      - challenge
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
