version: '3.5'
services:
  app:
    image: $chad_docker_registry/challenges/locked_out_2
    environment:
      - CHALLENGE_IP=192.168.146.1/17
    networks:
      - challenge
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
