version: '3.5'
services:
  server:
    image: $chad_docker_registry/challenges/smell_3_server
    environment:
      - CHALLENGE_IP=192.168.143.1/17
    networks:
      - challenge
  client:
    image: $chad_docker_registry/challenges/smell_3_client
    environment:
      - CHALLENGE_IP=192.168.143.2/17
    networks:
      - challenge
